name: DiffiApp
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    macOS: "14.6"

targets:
  DiffiApp:
    type: application
    platform: macOS
    sources:
      - Sources/DiffiApp
    dependencies:
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: Diffi
        product: Diffi
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.Diffi
      MACOSX_DEPLOYMENT_TARGET: "14.6"
      SWIFT_VERSION: "5.9"
      ENABLE_HARDENED_RUNTIME: true
      CODE_SIGN_ENTITLEMENTS: Diffi.entitlements
      GENERATE_INFOPLIST_FILE: true
      INFOPLIST_KEY_CFBundleDisplayName: "Diffi"
      INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.developer-tools"
      INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2024"
      OTHER_LDFLAGS: "-lz -liconv"

packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: "1.7.0"
  Diffi:
    path: .
